export const dynamic = "force-dynamic";
// app/api/admin/seed/route.ts

import { NextRequest, NextResponse } from "next/server";
import db from "@/lib/db";

const ADMIN_SECRET = process.env.ADMIN_SECRET;
const EVENT_CODE = "NAI5";

const PROFILES = [
  // ── Real BNC 2026 speakers ────────────────────────────────────────
  {
    pubkey: "bnc_bitange",
    name: "Bitange",
    role: "Researcher",
    location: "Nairobi, Kenya",
    core_vibe: "Deep Research",
    building: "Policy frameworks for digital finance in Kenya. Professor of Entrepreneurship at University of Nairobi.",
    needs: "Founders bridging grassroots Bitcoin adoption and regulatory dialogue.",
    interests: ["#bitcoin", "#africa", "#impact", "#community", "#fintech"],
  },
  {
    pubkey: "bnc_noelyne",
    name: "Noelyne",
    role: "Founder",
    location: "Nairobi, Kenya",
    core_vibe: "Ship Mode",
    building: "Ark Node AI — AI tools for Bitcoin node operators in emerging markets.",
    needs: "ML engineers and data scientists interested in Bitcoin infrastructure.",
    interests: ["#ai", "#bitcoin", "#open-source", "#africa", "#lightning"],
  },
  {
    pubkey: "bnc_everlyn",
    name: "Everlyn",
    role: "Community",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "Bitcoin Babies — empowering mothers in Nairobi's informal settlements through Bitcoin circular economy.",
    needs: "Partners for Bitcoin education in non-technical communities. Sponsors for the next cohort.",
    interests: ["#bitcoin", "#africa", "#community", "#impact", "#payments"],
  },
  {
    pubkey: "bnc_erik",
    name: "Erik",
    role: "Builder",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "Gridless — off-grid Bitcoin mining powered by stranded renewable energy across rural Africa.",
    needs: "Energy engineers and investors in sustainable African infrastructure.",
    interests: ["#bitcoin", "#africa", "#impact", "#open-source", "#startups"],
  },
  {
    pubkey: "bnc_rosaline",
    name: "Rosaline",
    role: "Founder",
    location: "Nairobi, Kenya",
    core_vibe: "Ship Mode",
    building: "Bitbiashara — enabling Kenyan small businesses to accept Bitcoin and Lightning payments.",
    needs: "Merchant acquirers and payment integrators focused on Africa.",
    interests: ["#bitcoin", "#lightning", "#fintech", "#africa", "#payments"],
  },
  {
    pubkey: "bnc_josef",
    name: "Josef",
    role: "Researcher",
    location: "Prague, Czech Republic",
    core_vibe: "Deep Research",
    building: "Trezor Academy — Bitcoin education for hardware wallet users worldwide.",
    needs: "Bitcoin educators building programs in Africa.",
    interests: ["#bitcoin", "#privacy", "#open-source", "#community"],
  },
  {
    pubkey: "bnc_jusper",
    name: "Jusper",
    role: "Researcher",
    location: "Nairobi, Kenya",
    core_vibe: "Deep Research",
    building: "Fossil Fuels for Africa — making the case for energy access and Bitcoin mining in Africa.",
    needs: "Energy economists and journalists covering African development.",
    interests: ["#bitcoin", "#africa", "#impact", "#community"],
  },
  {
    pubkey: "bnc_fidel",
    name: "Fidel",
    role: "Founder",
    location: "Nairobi, Kenya",
    core_vibe: "Ship Mode",
    building: "Bitika — peer-to-peer Bitcoin exchange for East Africa. Simple, fast, mobile-first.",
    needs: "Compliance and legal expertise in East African fintech regulation.",
    interests: ["#bitcoin", "#fintech", "#africa", "#payments", "#startups"],
  },
  {
    pubkey: "bnc_sabina",
    name: "Sabina",
    role: "Founder",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "Tando — Bitcoin savings and payments for the East African market.",
    needs: "Product designers and growth marketers who understand the Kenyan consumer.",
    interests: ["#bitcoin", "#lightning", "#fintech", "#africa", "#community"],
  },
  {
    pubkey: "bnc_christophe",
    name: "Christophe",
    role: "Community",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "BridgeSat Academy — connecting diaspora Bitcoin knowledge with East African communities.",
    needs: "Curriculum developers and diaspora Bitcoiners who want to give back.",
    interests: ["#bitcoin", "#africa", "#community", "#impact", "#lightning"],
  },
  {
    pubkey: "bnc_sharon",
    name: "Sharon",
    role: "Community",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "Btrust — Bitcoin developer grants and education programs across Africa.",
    needs: "Journalists and content creators interested in Bitcoin. Developers applying for grants.",
    interests: ["#bitcoin", "#africa", "#community", "#content", "#impact"],
  },
  {
    pubkey: "bnc_linda",
    name: "Linda",
    role: "Community",
    location: "Nairobi, Kenya",
    core_vibe: "Ship Mode",
    building: "Bitsavers Eduhub — Bitcoin financial literacy for students and young professionals in Kenya.",
    needs: "School and university partnerships. Curriculum sponsors.",
    interests: ["#bitcoin", "#africa", "#community", "#impact", "#content"],
  },
  {
    pubkey: "bnc_edith",
    name: "Edith",
    role: "Community",
    location: "Kampala, Uganda",
    core_vibe: "High Leverage",
    building: "Nile Bitcoin Community — growing Bitcoin adoption across Uganda.",
    needs: "Bitcoin businesses interested in Uganda expansion.",
    interests: ["#bitcoin", "#africa", "#community", "#impact", "#payments"],
  },
  {
    pubkey: "bnc_brindon",
    name: "Brindon",
    role: "Builder",
    location: "Kampala, Uganda",
    core_vibe: "Ship Mode",
    building: "Gorilla Sats — Bitcoin circular economy and merchant adoption network in Uganda.",
    needs: "Growth hackers and merchant POS solutions for East Africa.",
    interests: ["#bitcoin", "#lightning", "#africa", "#community", "#payments"],
  },
  {
    pubkey: "bnc_wycliffe",
    name: "Wycliffe",
    role: "Founder",
    location: "Nairobi, Kenya",
    core_vibe: "Ship Mode",
    building: "Kaze — Bitcoin remittance and cross-border payments for the East African corridor.",
    needs: "Compliance advisors in Kenya, Uganda, Tanzania. Other remittance founders.",
    interests: ["#bitcoin", "#lightning", "#payments", "#fintech", "#africa"],
  },
  {
    pubkey: "bnc_angella",
    name: "Angella",
    role: "Community",
    location: "Kampala, Uganda",
    core_vibe: "High Leverage",
    building: "School of Satoshi — Bitcoin education in Uganda, focused on women and underserved communities.",
    needs: "Sponsors for education materials. Bitcoin educators across East Africa.",
    interests: ["#bitcoin", "#africa", "#community", "#impact", "#content"],
  },
  {
    pubkey: "bnc_hanan",
    name: "Hanan",
    role: "Community",
    location: "London, UK",
    core_vibe: "High Leverage",
    building: "Bitcoin SheLeads — global network empowering women in Bitcoin.",
    needs: "Female Bitcoin founders across Africa. Institutional partners for women-in-Bitcoin programs.",
    interests: ["#bitcoin", "#community", "#impact", "#africa", "#investing"],
  },
  {
    pubkey: "bnc_isaack",
    name: "Isaack",
    role: "Builder",
    location: "Nairobi, Kenya",
    core_vibe: "Deep Research",
    building: "Minmo — Bitcoin infrastructure and Lightning reliability tooling.",
    needs: "Lightning engineers and node operators.",
    interests: ["#bitcoin", "#lightning", "#open-source", "#privacy"],
  },
  {
    pubkey: "bnc_laban",
    name: "Laban",
    role: "Operator",
    location: "Prague, Czech Republic",
    core_vibe: "High Leverage",
    building: "Braiins — Bitcoin mining software. Business development for African market entry.",
    needs: "Mining operators and energy entrepreneurs in East Africa.",
    interests: ["#bitcoin", "#africa", "#startups", "#open-source"],
  },
  {
    pubkey: "bnc_jason",
    name: "Jason",
    role: "Builder",
    location: "Nairobi, Kenya",
    core_vibe: "Ship Mode",
    building: "Tando — Bitcoin payments and savings for East Africa.",
    needs: "Backend engineers with Lightning experience. QA testers in Kenya.",
    interests: ["#bitcoin", "#lightning", "#open-source", "#fintech", "#africa"],
  },
  // ── Additional attendee profiles ──────────────────────────────────
  {
    pubkey: "bnc_amina",
    name: "Amina",
    role: "Founder",
    location: "Nairobi, Kenya",
    core_vibe: "Ship Mode",
    building: "Mobile-first Lightning wallet designed for feature phones in rural Kenya.",
    needs: "Hardware partners and offline-capable payment solutions.",
    interests: ["#lightning", "#bitcoin", "#africa", "#payments", "#fintech"],
  },
  {
    pubkey: "bnc_kofi",
    name: "Kofi",
    role: "Builder",
    location: "Accra, Ghana",
    core_vibe: "Deep Research",
    building: "Open-source Bitcoin node distribution optimised for low-bandwidth West African networks.",
    needs: "Distributed systems engineers and community testers across Africa.",
    interests: ["#bitcoin", "#open-source", "#africa", "#privacy", "#lightning"],
  },
  {
    pubkey: "bnc_priya",
    name: "Priya",
    role: "Investor",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "Portfolio of Bitcoin-native infrastructure plays in emerging markets.",
    needs: "Pre-seed founders building tools that work without reliable internet.",
    interests: ["#investing", "#bitcoin", "#africa", "#startups", "#impact"],
  },
  {
    pubkey: "bnc_david",
    name: "David",
    role: "Journalist",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "Bitcoin journalism covering East African adoption stories for international audiences.",
    needs: "Founders and operators with compelling stories. Data on Bitcoin adoption metrics.",
    interests: ["#bitcoin", "#africa", "#content", "#community", "#impact"],
  },
  {
    pubkey: "bnc_grace",
    name: "Grace",
    role: "Operator",
    location: "Kigali, Rwanda",
    core_vibe: "High Leverage",
    building: "Bitcoin circular economy pilot in Kigali — 80+ merchants, 200+ users.",
    needs: "POS integrations for cheap Android hardware. Co-marketing partners.",
    interests: ["#bitcoin", "#lightning", "#africa", "#community", "#impact"],
  },
  {
    pubkey: "bnc_omar",
    name: "Omar",
    role: "Builder",
    location: "Dar es Salaam, Tanzania",
    core_vibe: "Ship Mode",
    building: "Bitcoin remittance corridor between Tanzania and the Gulf. Early traction with diaspora workers.",
    needs: "Compliance partners in Tanzania and UAE. Lightning liquidity providers.",
    interests: ["#bitcoin", "#lightning", "#payments", "#africa", "#fintech"],
  },
  {
    pubkey: "bnc_fatuma",
    name: "Fatuma",
    role: "Community",
    location: "Mombasa, Kenya",
    core_vibe: "High Leverage",
    building: "Bitcoin circular economy for coastal Kenya — hotels, restaurants and tour operators accepting sats.",
    needs: "Tourist-facing Bitcoin onboarding tools. Hospitality sector partners.",
    interests: ["#bitcoin", "#payments", "#africa", "#community", "#impact"],
  },
  {
    pubkey: "bnc_samuel",
    name: "Samuel",
    role: "Builder",
    location: "Lagos, Nigeria",
    core_vibe: "Ship Mode",
    building: "Lightning payment SDK for Nigerian fintechs. Plug-and-play integration for existing apps.",
    needs: "Fintech partnerships and pilot customers in Nigeria and Kenya.",
    interests: ["#lightning", "#bitcoin", "#fintech", "#africa", "#open-source"],
  },
  {
    pubkey: "bnc_aisha",
    name: "Aisha",
    role: "Researcher",
    location: "Dakar, Senegal",
    core_vibe: "Deep Research",
    building: "Academic research on Bitcoin adoption in francophone West Africa.",
    needs: "Practitioners to interview — founders, operators, anyone running Bitcoin businesses.",
    interests: ["#bitcoin", "#africa", "#community", "#privacy", "#impact"],
  },
  {
    pubkey: "bnc_tobias",
    name: "Tobias",
    role: "Builder",
    location: "Stockholm, Sweden",
    core_vibe: "Deep Research",
    building: "Hardware wallet firmware with focus on air-gapped signing for high-value custody.",
    needs: "Security researchers and cryptographers. People building in constrained environments.",
    interests: ["#bitcoin", "#privacy", "#open-source", "#ai"],
  },
  {
    pubkey: "bnc_mercy",
    name: "Mercy",
    role: "Enthusiast",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "Bitcoin education content in Swahili for YouTube and TikTok. 12K followers.",
    needs: "Technical co-creator. Sponsors for a Swahili Bitcoin podcast.",
    interests: ["#bitcoin", "#content", "#africa", "#community", "#lightning"],
  },
  {
    pubkey: "bnc_pierre",
    name: "Pierre",
    role: "Investor",
    location: "Paris, France",
    core_vibe: "High Leverage",
    building: "Africa-focused Bitcoin fund. First closes in Kenya and Nigeria.",
    needs: "Deal flow — founders at pre-seed and seed building Bitcoin-native tools.",
    interests: ["#investing", "#bitcoin", "#africa", "#startups", "#fintech"],
  },
  {
    pubkey: "bnc_zawadi",
    name: "Zawadi",
    role: "Artist",
    location: "Nairobi, Kenya",
    core_vibe: "Hyper-Focused",
    building: "Digital art platform where Kenyan artists get paid in Bitcoin. First cohort launching soon.",
    needs: "Bitcoin payment rails that work for micropayments. Artist community partners.",
    interests: ["#bitcoin", "#art", "#africa", "#lightning", "#community"],
  },
  {
    pubkey: "bnc_brian",
    name: "Brian",
    role: "Builder",
    location: "Nairobi, Kenya",
    core_vibe: "Ship Mode",
    building: "Point-of-sale terminal for African markets that accepts M-Pesa and Lightning side by side.",
    needs: "Hardware manufacturers and merchant pilots in Nairobi.",
    interests: ["#bitcoin", "#lightning", "#payments", "#africa", "#fintech"],
  },
  {
    pubkey: "bnc_agnes",
    name: "Agnes",
    role: "Operator",
    location: "Kampala, Uganda",
    core_vibe: "High Leverage",
    building: "Women-led Bitcoin savings group network across Uganda. 400+ members.",
    needs: "Bitcoin-native savings products. Microfinance partners.",
    interests: ["#bitcoin", "#community", "#africa", "#impact", "#payments"],
  },
  {
    pubkey: "bnc_rafael",
    name: "Rafael",
    role: "Builder",
    location: "São Paulo, Brazil",
    core_vibe: "Ship Mode",
    building: "Cross-border payment corridor between Brazil and Kenya using Lightning.",
    needs: "M-Pesa or mobile money API experience. Lightning devs for integrations.",
    interests: ["#lightning", "#bitcoin", "#fintech", "#payments", "#open-source"],
  },
  {
    pubkey: "bnc_joyce",
    name: "Joyce",
    role: "Researcher",
    location: "Nairobi, Kenya",
    core_vibe: "Deep Research",
    building: "Economic research on Bitcoin as a savings tool for low-income households in Kenya.",
    needs: "Data partners and Bitcoin businesses willing to share anonymised transaction data.",
    interests: ["#bitcoin", "#africa", "#impact", "#fintech", "#community"],
  },
  {
    pubkey: "bnc_hassan",
    name: "Hassan",
    role: "Builder",
    location: "Mogadishu, Somalia",
    core_vibe: "Ship Mode",
    building: "Bitcoin remittance app for the Somali diaspora. Targeting hawala corridors.",
    needs: "Compliance experts. Lightning liquidity in USD and KES corridors.",
    interests: ["#bitcoin", "#lightning", "#payments", "#africa", "#fintech"],
  },
  {
    pubkey: "bnc_ruth",
    name: "Ruth",
    role: "Community",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "Bitcoin literacy programme for Kenyan secondary schools. Piloting in 5 schools.",
    needs: "Education technology partners. Bitcoin businesses to sponsor school kits.",
    interests: ["#bitcoin", "#community", "#africa", "#impact", "#content"],
  },
  {
    pubkey: "bnc_felix",
    name: "Felix",
    role: "Builder",
    location: "Nairobi, Kenya",
    core_vibe: "Deep Research",
    building: "Nostr-based identity layer for East African Bitcoin users. Working prototype.",
    needs: "Protocol engineers. Wallet teams interested in Nostr integration.",
    interests: ["#bitcoin", "#open-source", "#privacy", "#africa", "#lightning"],
  },
  {
    pubkey: "bnc_zainab",
    name: "Zainab",
    role: "Founder",
    location: "Nairobi, Kenya",
    core_vibe: "Ship Mode",
    building: "Islamic finance-compliant Bitcoin savings product for East African Muslims.",
    needs: "Sharia scholars and Islamic finance experts. Distribution partners.",
    interests: ["#bitcoin", "#fintech", "#africa", "#community", "#impact"],
  },
  {
    pubkey: "bnc_peter",
    name: "Peter",
    role: "Operator",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "Bitcoin mining cooperative for small-scale miners in East Africa.",
    needs: "Cheap and reliable energy sources. Mining hardware procurement partners.",
    interests: ["#bitcoin", "#africa", "#startups", "#open-source", "#impact"],
  },
  {
    pubkey: "bnc_wanjiru",
    name: "Wanjiru",
    role: "Designer",
    location: "Nairobi, Kenya",
    core_vibe: "Hyper-Focused",
    building: "UX design system for Bitcoin apps targeting first-time users in East Africa.",
    needs: "Technical co-founder who cares about accessibility and offline-first design.",
    interests: ["#design", "#bitcoin", "#africa", "#community", "#open-source"],
  },
  {
    pubkey: "bnc_michael",
    name: "Michael",
    role: "Builder",
    location: "Nairobi, Kenya",
    core_vibe: "Ship Mode",
    building: "Bitcoin payroll solution for Kenyan SMEs. Automates sats salary payments.",
    needs: "HR tech partnerships and accountants familiar with Bitcoin taxation in Kenya.",
    interests: ["#bitcoin", "#lightning", "#fintech", "#africa", "#startups"],
  },
  {
    pubkey: "bnc_esther",
    name: "Esther",
    role: "Journalist",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "East Africa Bitcoin news publication covering policy, adoption and builder stories.",
    needs: "Founders and operators with stories worth telling. Media partnership deals.",
    interests: ["#bitcoin", "#africa", "#content", "#community", "#impact"],
  },
  {
    pubkey: "bnc_ibrahim",
    name: "Ibrahim",
    role: "Builder",
    location: "Khartoum, Sudan",
    core_vibe: "Ship Mode",
    building: "Bitcoin as a financial lifeline for Sudanese under sanctions and currency collapse.",
    needs: "P2P exchange partners and humanitarian Bitcoin distribution experience.",
    interests: ["#bitcoin", "#africa", "#impact", "#community", "#privacy"],
  },
  {
    pubkey: "bnc_lucy",
    name: "Lucy",
    role: "Operator",
    location: "Nairobi, Kenya",
    core_vibe: "High Leverage",
    building: "Chama Bitcoin savings groups — digitising Kenya's traditional rotating savings model on Lightning.",
    needs: "Lightning developers familiar with multi-sig. Community finance partners.",
    interests: ["#bitcoin", "#lightning", "#community", "#africa", "#fintech"],
  },
  {
    pubkey: "bnc_nadia",
    name: "Nadia",
    role: "Founder",
    location: "Casablanca, Morocco",
    core_vibe: "Ship Mode",
    building: "Bitcoin exchange for North Africa with a focus on Morocco and Tunisia.",
    needs: "Regulatory advisors for North African markets. KYC/AML partners.",
    interests: ["#bitcoin", "#fintech", "#africa", "#startups", "#payments"],
  },
  {
    pubkey: "bnc_james",
    name: "James",
    role: "Builder",
    location: "Nairobi, Kenya",
    core_vibe: "Deep Research",
    building: "Lightning node routing optimisation for African network topology.",
    needs: "Network researchers and Lightning routing engineers.",
    interests: ["#bitcoin", "#lightning", "#open-source", "#africa", "#privacy"],
  },
  {
    pubkey: "bnc_ann",
    name: "Ann",
    role: "Community",
    location: "Kisumu, Kenya",
    core_vibe: "High Leverage",
    building: "Bitcoin circular economy in Kisumu — fishermen and market vendors accepting sats.",
    needs: "Simple POS tools that work on 2G. Bitcoin donations for community wallets.",
    interests: ["#bitcoin", "#payments", "#africa", "#community", "#impact"],
  },
];

export async function GET(request: NextRequest) {
  if (!ADMIN_SECRET) {
    return NextResponse.json({ error: "ADMIN_SECRET not configured" }, { status: 500 });
  }
  const secret = request.nextUrl.searchParams.get("secret");
  if (secret !== ADMIN_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const now = Date.now();
  const results: string[] = [];

  try {
    const insertUser = db.prepare(`
      INSERT INTO users (pubkey, npub, created_at, last_seen)
      VALUES (?, ?, ?, ?)
      ON CONFLICT(pubkey) DO UPDATE SET last_seen = excluded.last_seen
    `);

    const insertProfile = db.prepare(`
      INSERT INTO profiles (pubkey, name, role, location, core_vibe, building, needs, invite_code, interests, personality, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(pubkey) DO UPDATE SET
        name        = excluded.name,
        role        = excluded.role,
        location    = excluded.location,
        core_vibe   = excluded.core_vibe,
        building    = excluded.building,
        needs       = excluded.needs,
        invite_code = excluded.invite_code,
        interests   = excluded.interests,
        updated_at  = excluded.updated_at
    `);

    const seedAll = db.transaction(() => {
      for (const p of PROFILES) {
        insertUser.run(p.pubkey, `npub_${p.pubkey}`, now, now);
        insertProfile.run(
          p.pubkey, p.name, p.role, p.location, p.core_vibe,
          p.building, p.needs, EVENT_CODE,
          JSON.stringify(p.interests),
          JSON.stringify({ energy: 50, purpose: 50, thinking: 50, working: 50, journey: 50 }),
          now,
        );
        results.push(p.name);
      }
    });

    seedAll();

    return NextResponse.json({
      success: true,
      event_code: EVENT_CODE,
      seeded: results.length,
      profiles: results,
    });

  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
